package com.yehorychev.selenium.hooks;

import com.yehorychev.selenium.config.TestConfig;
import com.yehorychev.selenium.helpers.Logger;
import io.cucumber.java.BeforeAll;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

/**
 * Writes Allure environment.properties once before the suite runs — displays config in the Allure report.
 */
public class AllureEnvironmentHook {

    private static final Logger log = new Logger(AllureEnvironmentHook.class);

    /**
     * Runs once before any scenario in the suite.
     * Creates the allure-results directory if needed, then writes environment.properties.
     */
    @BeforeAll
    public static void writeAllureEnvironment() {
        try {
            Path dir = Paths.get(TestConfig.ALLURE_RESULTS_DIR);
            Files.createDirectories(dir);

            Properties env = new Properties();
            env.setProperty("Browser", TestConfig.BROWSER);
            env.setProperty("Headless", String.valueOf(TestConfig.HEADLESS));
            env.setProperty("Base URL", TestConfig.BASE_URL);
            env.setProperty("API Base URL", TestConfig.API_BASE_URL);
            env.setProperty("Threads", String.valueOf(TestConfig.PARALLEL_THREADS));
            env.setProperty("Retry Count", String.valueOf(TestConfig.RETRY_COUNT));
            env.setProperty("Timeout (ms)", String.valueOf(TestConfig.DEFAULT_TIMEOUT_MS));

            Path envFile = dir.resolve("environment.properties");
            try (OutputStream out = Files.newOutputStream(envFile)) {
                env.store(out, "Allure Environment — generated by AllureEnvironmentHook");
            }

            log.info("Allure environment.properties written to: " + envFile.toAbsolutePath());
        } catch (IOException e) {
            log.warn("Could not write Allure environment.properties: " + e.getMessage());
        }
    }
}
