package com.yehorychev.selenium.hooks;

import com.yehorychev.selenium.config.TestConfig;
import com.yehorychev.selenium.errors.FrameworkException;
import com.yehorychev.selenium.helpers.Logger;
import io.cucumber.java.BeforeAll;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.Properties;

/**
 * Suite-level setup hook — runs once before any scenario.
 * <ol>
 *   <li>Verifies the target environment is reachable (fast-fail on dead environments).</li>
 *   <li>Writes {@code environment.properties} for the Allure report.</li>
 *   <li>Copies {@code categories.json} from the classpath into allure-results.</li>
 * </ol>
 */
public class AllureEnvironmentHook {

    private static final Logger log = new Logger(AllureEnvironmentHook.class);
    private static final int HEALTH_CHECK_TIMEOUT_MS = 5_000;

    @BeforeAll
    public static void suiteSetUp() {
        healthCheck();
        writeAllureEnvironment();
        copyCategoriesJson();
    }

    // ── Health check ─────────────────────────────────────────────────────────

    private static void healthCheck() {
        String baseUrl = TestConfig.BASE_URL;
        log.step("Environment health check: " + baseUrl);
        try {
            HttpURLConnection conn = (HttpURLConnection) URI.create(baseUrl).toURL().openConnection();
            conn.setRequestMethod("HEAD");
            conn.setConnectTimeout(HEALTH_CHECK_TIMEOUT_MS);
            conn.setReadTimeout(HEALTH_CHECK_TIMEOUT_MS);
            conn.setInstanceFollowRedirects(true);
            int code = conn.getResponseCode();
            if (code >= 500) {
                throw new FrameworkException(
                        "Environment health check failed — " + baseUrl + " returned HTTP " + code);
            }
            log.info("Environment reachable: " + baseUrl + " → HTTP " + code);
        } catch (FrameworkException e) {
            throw e;
        } catch (Exception e) {
            throw new FrameworkException("Environment unreachable: " + baseUrl + " — " + e.getMessage(), e);
        }
    }

    // ── environment.properties ────────────────────────────────────────────────

    private static void writeAllureEnvironment() {
        try {
            Path dir = Paths.get(TestConfig.ALLURE_RESULTS_DIR);
            Files.createDirectories(dir);

            Properties env = new Properties();
            env.setProperty("Browser",         TestConfig.BROWSER);
            env.setProperty("Headless",        String.valueOf(TestConfig.HEADLESS));
            env.setProperty("Base URL",        TestConfig.BASE_URL);
            env.setProperty("API Base URL",    TestConfig.API_BASE_URL);
            env.setProperty("Threads",         String.valueOf(TestConfig.PARALLEL_THREADS));
            env.setProperty("Retry Count",     String.valueOf(TestConfig.RETRY_COUNT));
            env.setProperty("Timeout (ms)",    String.valueOf(TestConfig.DEFAULT_TIMEOUT_MS));
            env.setProperty("Remote",          String.valueOf(TestConfig.REMOTE_ENABLED));
            if (TestConfig.REMOTE_ENABLED) {
                env.setProperty("Grid URL",    TestConfig.REMOTE_URL);
            }
            env.setProperty("Java Version",    System.getProperty("java.version", "unknown"));
            env.setProperty("OS",              System.getProperty("os.name", "unknown")
                                               + " " + System.getProperty("os.arch", ""));

            Path envFile = dir.resolve("environment.properties");
            try (OutputStream out = Files.newOutputStream(envFile)) {
                env.store(out, "Allure Environment — generated by AllureEnvironmentHook");
            }
            log.info("Allure environment.properties written to: " + envFile.toAbsolutePath());
        } catch (IOException e) {
            log.warn("Could not write Allure environment.properties: " + e.getMessage());
        }
    }

    // ── categories.json ───────────────────────────────────────────────────────

    private static void copyCategoriesJson() {
        try (InputStream src = AllureEnvironmentHook.class
                .getClassLoader().getResourceAsStream("categories.json")) {
            if (src == null) {
                log.debug("categories.json not found on classpath — skipping");
                return;
            }
            Path dest = Paths.get(TestConfig.ALLURE_RESULTS_DIR, "categories.json");
            Files.copy(src, dest, StandardCopyOption.REPLACE_EXISTING);
            log.info("Allure categories.json copied to: " + dest.toAbsolutePath());
        } catch (IOException e) {
            log.warn("Could not copy categories.json: " + e.getMessage());
        }
    }
}
